markdown: kramdown
language: 'ko-kr'
plugins: [jekyll-feed]

name: 'Kwangsoo Shin'
description: ""


short_url: 'kwangsooshin.github.io'
base_url: /

social-email: ksshin@kakao.com
social-github: kwangsooshin
social-linkedin: kwangsooshin

collections:
  resume:
    permalink: "/resume/"
    output: true
